import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#13131b',
        surface: '#13131b',
        'surface-dim': '#13131b',
        'surface-bright': '#393841',
        'surface-container-lowest': '#0d0d15',
        'surface-container-low': '#1b1b23',
        'surface-container': '#1f1f27',
        'surface-container-high': '#292932',
        'surface-container-highest': '#34343d',
        'surface-variant': '#34343d',
        'on-surface': '#e4e1ed',
        'on-surface-variant': '#c7c4d7',
        'on-background': '#e4e1ed',
        'inverse-surface': '#e4e1ed',
        'inverse-on-surface': '#303038',
        outline: '#908fa0',
        'outline-variant': '#464554',
        primary: '#c0c1ff',
        'on-primary': '#1000a9',
        'primary-container': '#8083ff',
        'on-primary-container': '#0d0096',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'inverse-primary': '#494bd6',
        secondary: '#ddb7ff',
        'on-secondary': '#490080',
        'secondary-container': '#6f00be',
        'on-secondary-container': '#d6a9ff',
        'secondary-fixed': '#f0dbff',
        'secondary-fixed-dim': '#ddb7ff',
        'on-secondary-fixed': '#2c0051',
        'on-secondary-fixed-variant': '#6900b3',
        tertiary: '#ffb783',
        'on-tertiary': '#4f2500',
        'tertiary-container': '#d97721',
        'on-tertiary-container': '#452000',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#703700',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '12px',
        'container-margin': '20px',
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', '"PingFang SC"', '"Noto Sans SC"', 'system-ui', 'sans-serif'],
        body: ['"Be Vietnam Pro"', '"PingFang SC"', '"Noto Sans SC"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      boxShadow: {
        'glow-primary': '0 0 20px rgba(192, 193, 255, 0.25)',
        'glow-secondary': '0 0 20px rgba(221, 183, 255, 0.25)',
        'glow-tertiary': '0 0 20px rgba(255, 183, 131, 0.25)',
        'glow-error': '0 0 20px rgba(255, 180, 171, 0.3)',
      },
    },
  },
  plugins: [],
};

export default config;
